/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Utilidades.Procesa;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.JFileChooser;

/**
 *
 * @author Christian
 */
public class UI extends javax.swing.JFrame {

    private Procesa objProcesa = new Procesa();

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemGuardarC = new javax.swing.JMenuItem();
        jMenuItemQuitar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("UI/Bundle"); // NOI18N
        setTitle(bundle.getString("UI.title")); // NOI18N

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setEnabled(false);
        jScrollPane.setViewportView(jTextArea);

        jButtonEnviar.setText(bundle.getString("UI.jButtonEnviar.text")); // NOI18N
        jButtonEnviar.setEnabled(false);
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jTextField.setEnabled(false);

        jMenuArchivo.setText(bundle.getString("UI.jMenuArchivo.text")); // NOI18N

        jMenuItemCargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCargar.setText(bundle.getString("UI.jMenuItemCargar.text")); // NOI18N
        jMenuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCargar);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setText(bundle.getString("UI.jMenuItemGuardar.text")); // NOI18N
        jMenuItemGuardar.setEnabled(false);
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemGuardarC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardarC.setText(bundle.getString("UI.jMenuItemGuardarC.text")); // NOI18N
        jMenuItemGuardarC.setEnabled(false);
        jMenuItemGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarCActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardarC);

        jMenuItemQuitar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuitar.setText(bundle.getString("UI.jMenuItemQuitar.text")); // NOI18N
        jMenuItemQuitar.setEnabled(false);
        jMenuItemQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemQuitar);

        jMenuBar.add(jMenuArchivo);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnviar)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitarActionPerformed
        jMenuItemGuardar.setEnabled(false);
        jMenuItemGuardarC.setEnabled(false);
        jMenuItemQuitar.setEnabled(false);
        jTextArea.setText("");
        jTextArea.setEnabled(false);
        jTextField.setText("");
        jTextField.setEnabled(false);
        jButtonEnviar.setEnabled(false);
        objProcesa = new Procesa();
    }//GEN-LAST:event_jMenuItemQuitarActionPerformed

    private void jMenuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarActionPerformed
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                objProcesa = Utilidades.Archivo.leerArchivo(jFileChooser.getSelectedFile().getPath());
                jMenuItemGuardar.setEnabled(true);
                jMenuItemGuardarC.setEnabled(true);
                jMenuItemQuitar.setEnabled(true);
                jTextArea.setText("Base de conocimiento cargada");
                jTextArea.setEnabled(true);
                jTextField.setText("");
                jTextField.setEnabled(true);
                jButtonEnviar.setEnabled(true);
            } catch (ParseException ex) {
                jTextArea.append(ex.getMessage() + "\n");
            } catch (Exception ex) {
                jTextArea.append(ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_jMenuItemCargarActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        try {
            Utilidades.Archivo.escribirArchivo(jFileChooser.getSelectedFile().getPath(), objProcesa);
        } catch (IOException ex) {
            jTextArea.append(ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarCActionPerformed
        if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                Utilidades.Archivo.escribirArchivo(jFileChooser.getSelectedFile().getPath(), objProcesa);
            } catch (IOException ex) {
                jTextArea.append(ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_jMenuItemGuardarCActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        objProcesa.procesarCadena(jTextField.getText());
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemGuardarC;
    private javax.swing.JMenuItem jMenuItemQuitar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
